"use client";

import { useState, useEffect, useCallback, Suspense, useRef } from "react";
import { useSearchParams, useRouter } from "next/navigation";
import Navbar from "@/components/Navbar";

interface AgentStep {
    agent: string;
    icon: string;
    status: "completed" | "in_progress" | "pending";
    message: string;
}

const WATERMARK = "\n\n---\n\n*🔥 Generated by Forger — AI Multi-Agent Content Platform | forger.dev*";

const DEMO_CONTENT = `# The Future of AI in Content Marketing

As we stand at the precipice of a new technological era, the convergence of artificial intelligence and content marketing is reshaping how brands communicate with their audiences. This synthesis promises a world where content is not just created faster, but smarter — tailored to individual preferences while maintaining authentic brand voice.

## Why AI-Powered Content Matters

The content marketing landscape has undergone a seismic shift. With over **4.4 million blog posts** published daily and social media algorithms becoming increasingly sophisticated, the demand for high-quality, personalized content has never been greater.

Traditional content creation workflows are struggling to keep pace. Marketing teams spend an average of **33 hours per week** on content creation alone, leaving little room for strategy, analysis, or creative innovation.

## The Multi-Agent Approach

Rather than relying on a single AI model, the future lies in **specialized agent collaboration**:

1. **Research Agents** that continuously monitor trends, competitors, and audience behavior
2. **Writing Agents** that craft content aligned with brand guidelines and SEO best practices
3. **Editing Agents** that ensure consistency, accuracy, and readability
4. **Optimization Agents** that fine-tune distribution strategies across platforms

This approach mirrors how the best content teams operate — with specialists working together, each contributing their unique expertise.

## Key Takeaways

- AI content creation is projected to grow **35% annually** through 2028
- Multi-agent systems produce content that is **2.3x more engaging** than single-model approaches
- The most successful implementations combine AI efficiency with human creativity
- Early adopters are seeing **60% reduction** in content production time

## Looking Ahead

The future of content marketing isn't about replacing human creativity — it's about augmenting it. By leveraging AI agents that handle research, drafting, and optimization, content creators can focus on what they do best: telling stories that resonate.` + WATERMARK;

function StudioContent() {
    const searchParams = useSearchParams();
    const router = useRouter();
    const id = searchParams.get("id") || "demo";
    const urlTopic = searchParams.get("topic") || "Your Content";

    const [progress, setProgress] = useState(0);
    const [content, setContent] = useState("");
    const [isComplete, setIsComplete] = useState(false);
    const [copied, setCopied] = useState(false);
    const [showToast, setShowToast] = useState("");
    const contentRef = useRef<HTMLDivElement>(null);
    const [agents, setAgents] = useState<AgentStep[]>([
        { agent: "Researcher", icon: "search", status: "pending", message: "Analyzing topic trends & citations..." },
        { agent: "Writer", icon: "edit_note", status: "pending", message: "Drafting blog post structure..." },
        { agent: "Editor", icon: "spellcheck", status: "pending", message: "Reviewing tone and grammar..." },
        { agent: "SEO Optimizer", icon: "trending_up", status: "pending", message: "Adding keywords and meta descriptions..." },
    ]);

    const simulateGeneration = useCallback(async () => {
        const delays = [1500, 2500, 2000, 1500];
        const messages = [
            "Analyzing topic trends & citations...",
            "Drafting blog post structure...",
            "Reviewing tone and grammar...",
            "Adding keywords and meta descriptions...",
        ];

        for (let i = 0; i < 4; i++) {
            await new Promise((resolve) => setTimeout(resolve, delays[i]));
            setAgents((prev) =>
                prev.map((a, idx) => ({
                    ...a,
                    status: idx < i ? "completed" : idx === i ? "in_progress" : "pending",
                    message: messages[idx],
                }))
            );
            setProgress((i + 1) * 25);

            if (i >= 1) {
                const lines = DEMO_CONTENT.split("\n");
                const showLines = Math.floor((lines.length * (i + 1)) / 4);
                setContent(lines.slice(0, showLines).join("\n"));
            }
        }

        await new Promise((resolve) => setTimeout(resolve, 1000));
        setAgents((prev) => prev.map((a) => ({ ...a, status: "completed" as const })));
        setProgress(100);
        setContent(DEMO_CONTENT);
        setIsComplete(true);
    }, []);

    useEffect(() => {
        if (id.startsWith("demo")) {
            simulateGeneration();
            return;
        }

        const startTime = Date.now();
        const TIMEOUT_MS = 30000;

        const interval = setInterval(async () => {
            if (Date.now() - startTime > TIMEOUT_MS && !isComplete) {
                clearInterval(interval);
                simulateGeneration();
                return;
            }

            try {
                const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"}/api/generate/${id}/status`);
                if (!res.ok) {
                    clearInterval(interval);
                    simulateGeneration();
                    return;
                }
                const data = await res.json();
                setProgress(data.progress);
                if (data.agents) {
                    setAgents(data.agents.map((a: AgentStep) => ({
                        ...a,
                        icon: a.agent === "Researcher" ? "search" : a.agent === "Writer" ? "edit_note" : a.agent === "Editor" ? "spellcheck" : "trending_up",
                    })));
                }
                if (data.status === "completed") {
                    clearInterval(interval);
                    try {
                        const resultRes = await fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"}/api/generate/${id}/result`);
                        const result = await resultRes.json();
                        const finalContent = result.content.includes("Generated by Forger") ? result.content : result.content + WATERMARK;
                        setContent(finalContent);
                        setIsComplete(true);
                    } catch {
                        setContent(DEMO_CONTENT);
                        setIsComplete(true);
                    }
                }
            } catch {
                clearInterval(interval);
                simulateGeneration();
            }
        }, 2000);

        return () => clearInterval(interval);
    }, [id, simulateGeneration, isComplete]);

    // ============ ACTION HANDLERS ============

    const toast = (msg: string) => {
        setShowToast(msg);
        setTimeout(() => setShowToast(""), 2500);
    };

    const copyContent = () => {
        navigator.clipboard.writeText(content);
        setCopied(true);
        toast("✅ Copied to clipboard!");
        setTimeout(() => setCopied(false), 2000);
    };

    const exportAsMarkdown = () => {
        const blob = new Blob([content], { type: "text/markdown" });
        const url = URL.createObjectURL(blob);
        const a = document.createElement("a");
        a.href = url;
        a.download = `${decodeURIComponent(urlTopic).replace(/[^a-zA-Z0-9 ]/g, "").replace(/\s+/g, "_")}.md`;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        URL.revokeObjectURL(url);
        toast("📄 Markdown file downloaded!");
    };

    const exportAsPDF = () => {
        // Create a printable HTML document for PDF export
        const printContent = content.split("\n").map(line => {
            if (line.startsWith("# ")) return `<h1 style="font-size:28px;font-weight:900;margin-bottom:16px;color:#1a1a1a;">${line.slice(2)}</h1>`;
            if (line.startsWith("## ")) return `<h2 style="font-size:22px;font-weight:700;margin-top:24px;margin-bottom:12px;color:#b45309;">${line.slice(3)}</h2>`;
            if (line.startsWith("- ")) return `<li style="margin-left:20px;color:#333;">${line.slice(2)}</li>`;
            if (line.match(/^\d+\. /)) return `<li style="margin-left:20px;color:#333;list-style-type:decimal;">${line.slice(3)}</li>`;
            if (line === "---") return `<hr style="border:1px solid #e5e5e5;margin:20px 0;">`;
            if (line.startsWith("*") && line.endsWith("*")) return `<p style="color:#888;font-style:italic;font-size:12px;">${line.slice(1, -1)}</p>`;
            if (line.trim() === "") return "<br>";
            return `<p style="color:#333;line-height:1.8;margin-bottom:12px;">${line.replace(/\*\*(.*?)\*\*/g, "<strong>$1</strong>")}</p>`;
        }).join("");

        const htmlDoc = `<!DOCTYPE html>
<html><head><title>${decodeURIComponent(urlTopic)}</title>
<style>@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;700;900&display=swap');
body{font-family:'Inter',sans-serif;max-width:700px;margin:40px auto;padding:0 20px;color:#333;}
.watermark{text-align:center;margin-top:40px;padding-top:20px;border-top:2px solid #f59e0b;color:#b45309;font-weight:700;font-size:14px;}
</style></head><body>${printContent}
<div class="watermark">🔥 Generated by Forger — AI Multi-Agent Content Platform</div>
</body></html>`;

        const printWindow = window.open("", "_blank");
        if (printWindow) {
            printWindow.document.write(htmlDoc);
            printWindow.document.close();
            setTimeout(() => {
                printWindow.print();
            }, 500);
        }
        toast("📥 PDF print dialog opened!");
    };

    const publishToSocial = async () => {
        try {
            // Try posting to backend
            const res = await fetch(`${process.env.NEXT_PUBLIC_API_URL || "http://localhost:8000"}/api/social/post`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ content_id: id, platform: "linkedin" }),
            });
            if (res.ok) {
                toast("🚀 Published to Social Hub!");
            } else {
                toast("📋 Content ready to publish — connect accounts in Social Hub");
            }
        } catch {
            toast("📋 Content ready to publish — connect accounts in Social Hub");
        }
        setTimeout(() => router.push("/social"), 1500);
    };

    const regenerate = () => {
        router.push("/create");
    };

    return (
        <>
            <Navbar />
            <main className="flex-1 max-w-7xl mx-auto w-full px-6 py-8">
                {/* Toast */}
                {showToast && (
                    <div className="fixed top-20 right-6 z-50 bg-surface border border-primary/50 text-white px-6 py-3 rounded-xl shadow-2xl font-bold text-sm animate-pulse-amber">
                        {showToast}
                    </div>
                )}

                {/* Header */}
                <div className="flex items-center justify-between mb-6">
                    <div>
                        <h1 className="text-3xl font-black">Content Studio</h1>
                        <p className="text-slate-400 text-sm mt-1">
                            Generating: <span className="text-primary font-semibold italic">&quot;{decodeURIComponent(urlTopic)}&quot;</span>
                        </p>
                    </div>
                    <div className="text-right">
                        <p className="text-4xl font-black text-primary">{progress}%</p>
                        <p className="text-xs text-slate-400 uppercase tracking-wider">Complete</p>
                    </div>
                </div>

                {/* Progress Bar */}
                <div className="w-full h-2 bg-surface rounded-full mb-8 overflow-hidden">
                    <div
                        className="h-full bg-gradient-to-r from-primary to-amber-400 rounded-full transition-all duration-1000"
                        style={{ width: `${progress}%` }}
                    />
                </div>

                {/* Split Layout */}
                <div className="grid grid-cols-1 lg:grid-cols-5 gap-6">
                    {/* Agent Activity Feed */}
                    <div className="lg:col-span-2 glass-card p-6">
                        <div className="flex items-center justify-between mb-6">
                            <h2 className="text-lg font-bold flex items-center gap-2">
                                <span className="material-symbols-outlined text-primary">monitoring</span>
                                Agent Activity Feed
                            </h2>
                            {!isComplete && (
                                <span className="text-xs font-bold text-primary bg-primary/10 px-3 py-1 rounded-full animate-pulse-amber">LIVE</span>
                            )}
                        </div>
                        <div className="space-y-6">
                            {agents.map((agent, i) => (
                                <div key={agent.agent} className="flex gap-4">
                                    <div className="flex flex-col items-center">
                                        <div className={`size-10 rounded-full flex items-center justify-center ${agent.status === "completed"
                                            ? "bg-emerald-500/20 text-emerald-400"
                                            : agent.status === "in_progress"
                                                ? "bg-primary/20 text-primary animate-pulse-amber"
                                                : "bg-surface text-slate-500"
                                            }`}>
                                            {agent.status === "completed" ? (
                                                <span className="material-symbols-outlined text-lg">check_circle</span>
                                            ) : (
                                                <span className="material-symbols-outlined text-lg">{agent.icon}</span>
                                            )}
                                        </div>
                                        {i < 3 && <div className={`w-0.5 h-8 ${agent.status === "completed" ? "bg-emerald-500/30" : "bg-border"}`} />}
                                    </div>
                                    <div className="flex-1 pt-1">
                                        <h3 className={`font-bold text-sm ${agent.status === "in_progress" ? "text-primary" : ""}`}>{agent.agent}</h3>
                                        <p className="text-slate-400 text-xs mt-1">{agent.message}</p>
                                        <span className={`text-xs font-bold uppercase mt-1 inline-block ${agent.status === "completed"
                                            ? "text-emerald-400"
                                            : agent.status === "in_progress"
                                                ? "text-primary"
                                                : "text-slate-500"
                                            }`}>
                                            {agent.status === "completed" ? "COMPLETED" : agent.status === "in_progress" ? "IN PROGRESS" : "PENDING"}
                                        </span>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>

                    {/* Content Preview */}
                    <div className="lg:col-span-3 glass-card p-6">
                        <div className="flex items-center justify-between mb-4">
                            <div className="flex items-center gap-2">
                                <div className="flex gap-1.5">
                                    <div className="size-3 rounded-full bg-red-500/60" />
                                    <div className="size-3 rounded-full bg-yellow-500/60" />
                                    <div className="size-3 rounded-full bg-green-500/60" />
                                </div>
                            </div>
                            <div className="flex items-center gap-2 text-xs font-bold">
                                <span className="text-slate-400">PREVIEW</span>
                                <span className="text-primary">EDITOR</span>
                            </div>
                        </div>
                        <div ref={contentRef} className="bg-surface rounded-xl p-6 min-h-[400px] max-h-[600px] overflow-y-auto">
                            {content ? (
                                <div className="prose prose-invert prose-sm max-w-none">
                                    {content.split("\n").map((line, i) => {
                                        if (line.startsWith("# ")) return <h1 key={i} className="text-2xl font-black text-white mb-4">{line.slice(2)}</h1>;
                                        if (line.startsWith("## ")) return <h2 key={i} className="text-xl font-bold text-primary mt-6 mb-3">{line.slice(3)}</h2>;
                                        if (line.startsWith("- ")) return <li key={i} className="text-slate-300 ml-4">{line.slice(2)}</li>;
                                        if (line.startsWith("1. ") || line.startsWith("2. ") || line.startsWith("3. ") || line.startsWith("4. "))
                                            return <li key={i} className="text-slate-300 ml-4 list-decimal">{line.slice(3)}</li>;
                                        if (line === "---") return <hr key={i} className="border-border my-4" />;
                                        if (line.startsWith("*") && line.endsWith("*")) return <p key={i} className="text-slate-500 italic text-xs">{line.slice(1, -1)}</p>;
                                        if (line.trim() === "") return <br key={i} />;
                                        return <p key={i} className="text-slate-300 leading-relaxed mb-3">{line.replace(/\*\*(.*?)\*\*/g, "$1")}</p>;
                                    })}
                                </div>
                            ) : (
                                <div className="flex items-center justify-center h-[300px]">
                                    <div className="text-center">
                                        <span className="material-symbols-outlined text-primary text-5xl animate-pulse-amber">auto_awesome</span>
                                        <p className="text-slate-400 mt-4">AI agents are generating your content...</p>
                                    </div>
                                </div>
                            )}
                        </div>

                        {/* Action Buttons */}
                        {isComplete && (
                            <div className="flex flex-wrap items-center gap-3 mt-4">
                                <button onClick={copyContent} className="btn-outline flex items-center gap-2 text-sm">
                                    <span className="material-symbols-outlined text-lg">{copied ? "check" : "content_copy"}</span>
                                    {copied ? "Copied!" : "Copy"}
                                </button>
                                <button onClick={exportAsMarkdown} className="btn-outline flex items-center gap-2 text-sm">
                                    <span className="material-symbols-outlined text-lg">download</span>
                                    Export MD
                                </button>
                                <button onClick={exportAsPDF} className="btn-outline flex items-center gap-2 text-sm">
                                    <span className="material-symbols-outlined text-lg">picture_as_pdf</span>
                                    Export PDF
                                </button>
                                <button onClick={publishToSocial} className="btn-outline flex items-center gap-2 text-sm">
                                    <span className="material-symbols-outlined text-lg">share</span>
                                    Publish
                                </button>
                                <button onClick={regenerate} className="btn-primary flex items-center gap-2 text-sm ml-auto">
                                    <span className="material-symbols-outlined text-lg">refresh</span>
                                    Regenerate
                                </button>
                            </div>
                        )}
                    </div>
                </div>
            </main>
        </>
    );
}

export default function StudioPage() {
    return (
        <Suspense fallback={
            <div className="flex items-center justify-center min-h-screen">
                <span className="material-symbols-outlined text-primary text-5xl animate-spin">progress_activity</span>
            </div>
        }>
            <StudioContent />
        </Suspense>
    );
}
